"""EQUIPA package — modular extraction of forge_orchestrator.py.

Phase 1 leaf modules: constants, checkpoints, git_ops.
All public symbols are re-exported here for backward compatibility.

Copyright 2026 Forgeborn
"""

from __future__ import annotations

# --- Constants (equipa.constants) ---
from equipa.constants import (
    AUTOFIX_COST_LIMIT,
    AUTOFIX_DEBUGGER_BUDGET,
    AUTOFIX_MAX_DEBUGGER_CYCLES,
    AUTOFIX_PLANNER_BUDGET,
    BUDGET_CHECK_INTERVAL,
    BUDGET_CRITICAL_THRESHOLD,
    BUDGET_HALFWAY_THRESHOLD,
    CHECKPOINT_DIR,
    COMPLEXITY_MULTIPLIERS,
    COST_ESTIMATE_PER_TURN,
    COST_LIMITS,
    DEFAULT_MAX_RETRIES,
    DEFAULT_MAX_TURNS,
    DEFAULT_MODEL,
    DEFAULT_ROLE_MODELS,
    DEFAULT_ROLE_TURNS,
    DEV_COMPACTION_THRESHOLD,
    DYNAMIC_BUDGET_BLOCKED_RATIO,
    DYNAMIC_BUDGET_EXTEND_TURNS,
    DYNAMIC_BUDGET_MIN_TURNS,
    DYNAMIC_BUDGET_START_RATIO,
    EARLY_TERM_EXEMPT_ROLES,
    EARLY_TERM_FINAL_WARN_TURNS,
    EARLY_TERM_KILL_TURNS,
    EARLY_TERM_STUCK_PHRASES,
    EARLY_TERM_WARN_TURNS,
    GITHUB_OWNER,
    GITIGNORE_TEMPLATES,
    MAX_CONTINUATIONS,
    MAX_DEV_TEST_CYCLES,
    MAX_FOLLOWUP_TASKS,
    MAX_MANAGER_ROUNDS,
    MAX_TASKS_PER_PLAN,
    MCP_CONFIG,
    MONOLOGUE_EXEMPT_TURNS,
    MONOLOGUE_THRESHOLD,
    NO_PROGRESS_LIMIT,
    PREFLIGHT_SKIP_KEYWORDS,
    PREFLIGHT_TIMEOUT,
    PRIORITY_ORDER,
    PROCESS_TIMEOUT,
    PROJECT_DIRS,
    PROMPTS_DIR,
    ROLE_PROMPTS,
    ROLE_SKILLS,
    SKILL_MANIFEST_FILE,
    SKILLS_BASE_DIR,
    TESTER_COMPACTION_THRESHOLD,
    THEFORGE_DB,
)

# --- Checkpoints (equipa.checkpoints) ---
from equipa.checkpoints import (
    clear_checkpoints,
    load_checkpoint,
    save_checkpoint,
)

# --- Git Operations (equipa.git_ops) ---
from equipa.git_ops import (
    _get_repo_env,
    _git_run,
    _is_git_repo,
    check_gh_installed,
    detect_project_language,
    setup_all_repos,
    setup_single_repo,
)

__all__ = [
    # Constants
    "AUTOFIX_COST_LIMIT",
    "AUTOFIX_DEBUGGER_BUDGET",
    "AUTOFIX_MAX_DEBUGGER_CYCLES",
    "AUTOFIX_PLANNER_BUDGET",
    "BUDGET_CHECK_INTERVAL",
    "BUDGET_CRITICAL_THRESHOLD",
    "BUDGET_HALFWAY_THRESHOLD",
    "CHECKPOINT_DIR",
    "COMPLEXITY_MULTIPLIERS",
    "COST_ESTIMATE_PER_TURN",
    "COST_LIMITS",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_MAX_TURNS",
    "DEFAULT_MODEL",
    "DEFAULT_ROLE_MODELS",
    "DEFAULT_ROLE_TURNS",
    "DEV_COMPACTION_THRESHOLD",
    "DYNAMIC_BUDGET_BLOCKED_RATIO",
    "DYNAMIC_BUDGET_EXTEND_TURNS",
    "DYNAMIC_BUDGET_MIN_TURNS",
    "DYNAMIC_BUDGET_START_RATIO",
    "EARLY_TERM_EXEMPT_ROLES",
    "EARLY_TERM_FINAL_WARN_TURNS",
    "EARLY_TERM_KILL_TURNS",
    "EARLY_TERM_STUCK_PHRASES",
    "EARLY_TERM_WARN_TURNS",
    "GITHUB_OWNER",
    "GITIGNORE_TEMPLATES",
    "MAX_CONTINUATIONS",
    "MAX_DEV_TEST_CYCLES",
    "MAX_FOLLOWUP_TASKS",
    "MAX_MANAGER_ROUNDS",
    "MAX_TASKS_PER_PLAN",
    "MCP_CONFIG",
    "MONOLOGUE_EXEMPT_TURNS",
    "MONOLOGUE_THRESHOLD",
    "NO_PROGRESS_LIMIT",
    "PREFLIGHT_SKIP_KEYWORDS",
    "PREFLIGHT_TIMEOUT",
    "PRIORITY_ORDER",
    "PROCESS_TIMEOUT",
    "PROJECT_DIRS",
    "PROMPTS_DIR",
    "ROLE_PROMPTS",
    "ROLE_SKILLS",
    "SKILL_MANIFEST_FILE",
    "SKILLS_BASE_DIR",
    "TESTER_COMPACTION_THRESHOLD",
    "THEFORGE_DB",
    # Checkpoints
    "clear_checkpoints",
    "load_checkpoint",
    "save_checkpoint",
    # Git Operations
    "_get_repo_env",
    "_git_run",
    "_is_git_repo",
    "check_gh_installed",
    "detect_project_language",
    "setup_all_repos",
    "setup_single_repo",
]
